export const CATEGORIES = [
  "Groceries",
  "Dining",
  "Transportation",
  "Entertainment",
  "Shopping",
  "Utilities",
  "Healthcare",
  "Travel",
  "Education",
  "Personal Care",
  "Home",
  "Subscriptions",
  "Other",
] as const;

export type Category = (typeof CATEGORIES)[number];

export const CATEGORY_ALIASES: Record<string, Category> = {
  food: "Groceries",
  grocery: "Groceries",
  supermarket: "Groceries",
  restaurant: "Dining",
  cafe: "Dining",
  coffee: "Dining",
  lunch: "Dining",
  dinner: "Dining",
  breakfast: "Dining",
  uber: "Transportation",
  lyft: "Transportation",
  taxi: "Transportation",
  gas: "Transportation",
  fuel: "Transportation",
  petrol: "Transportation",
  bus: "Transportation",
  train: "Transportation",
  metro: "Transportation",
  subway: "Transportation",
  movie: "Entertainment",
  movies: "Entertainment",
  cinema: "Entertainment",
  netflix: "Subscriptions",
  spotify: "Subscriptions",
  subscription: "Subscriptions",
  clothes: "Shopping",
  clothing: "Shopping",
  electronics: "Shopping",
  amazon: "Shopping",
  electric: "Utilities",
  electricity: "Utilities",
  water: "Utilities",
  internet: "Utilities",
  phone: "Utilities",
  doctor: "Healthcare",
  pharmacy: "Healthcare",
  medicine: "Healthcare",
  medical: "Healthcare",
  hospital: "Healthcare",
  hotel: "Travel",
  flight: "Travel",
  airbnb: "Travel",
  course: "Education",
  book: "Education",
  books: "Education",
  tuition: "Education",
  haircut: "Personal Care",
  salon: "Personal Care",
  spa: "Personal Care",
  gym: "Personal Care",
  furniture: "Home",
  repair: "Home",
  maintenance: "Home",
  rent: "Home",
};
